# Changes here will be overwritten by Copier.
_commit: 1.12.1
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: "Timothée Mazzucotelli"
author_username: pawamoy
copyright_date: '2020'
copyright_holder: "Timothée Mazzucotelli"
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
project_description: 'My personal Telegram bot: aria2 management, torrent sites crawling,
    media organization with mvodb and Plex, etc.'
project_name: pawabot
python_package_command_line_name: pawabot
python_package_distribution_name: pawabot
python_package_import_name: pawabot
repository_name: pawabot
repository_namespace: pawamoy
repository_provider: github.com

